### ISSUE TITLE
pingExec return false in win8.1

### ISSUE THREAD

**Issue by egmsystems** [geerlingguy/Ping#30]
in line 111 
$output[1] have  string(53) "Respuesta desde 127.0.0.1: bytes=32 tiempo<1m TTL=128"

$response = preg_match("/time(?:=|<)(?<time>[\.0-9]+)(?:|\s)ms/", $output[1], $matches);

var_dump($response,$matches);
int(0)
array(0) {
}

**Comment by sergiowww** [comment]
This problem is related to the OS native language, the ping class uses a regex that matches the word "time", in this sense, it won't match "tiempo" or "tempo". I've made some changes in my local code just to make it work for portuguese, but we need to figure out a better regex pattern to match all "time" translations across different OS, or develop an internationalization approach...

**Comment by geerlingguy** [comment]
See #5 - Supporting the ability to have Ping run with different languages would fix this issue (or as a stopgap, at least having the regex text be able to vary on language).

**Comment by lubber-de** [comment]
@egmsystems 
With #50 you could do this

```php
$ping = new Ping('fomantic-ui.com');
$ping->setKeyword('tiempo');
$ptime = $ping->ping();
```
