### ISSUE TITLE
Ping Fail when below 0

### ISSUE THREAD

**Issue by digi128pci** [geerlingguy/Ping#48]
Ping Fails when latency is below 0.5.

Reason:

$latency = round($matches['time']);

When Time is 0.42 ms --> round --> 0 but host is alive!

I removed round() and its working !

**Comment by geerlingguy** [comment]
Hmm... seems like in testing, trying a `ping localhost` would be able to catch this (not really edge) case.

**Comment by geerlingguy** [comment]
Apparently my docs have been wrong all along—I say I'm returning an `int` for `$latency` when I'm actually returning a float with one decimal point of precision. I'm going to change the `round()` to use four decimals of precision (should get all but the most extreme edge cases; pinging localhost on a few of my machines and containers gives me `0.0X ms`), and update the docs.

Also need to fix some tests, been a while since I updated them.

**Comment by geerlingguy** [comment]
Should be fixed in 1.2.1!
